build_topic_model:
  stage: build_images
  variables:
    IMAGETAG: "$CI_REGISTRY/$CI_PROJECT_PATH/ai-library-topic-model:${CI_COMMIT_SHORT_SHA}"
  only:
    changes:
      - Makefile
      - .gitlab-ci.yml
      - topic_model/**/*
      - storage/**/*
    refs:
      - master
      - merge_requests
      - tags
      - branches
  services:
    - docker:dind
  script:
    - echo `env | sort`
    - cd topic_model
    - make build
    - docker push $IMAGETAG

test_topic_model:
  stage: test_models
  variables:
    IMAGETAG: "$CI_REGISTRY/$CI_PROJECT_PATH/ai-library-topic-model:${CI_COMMIT_SHORT_SHA}"
  only:
    changes:
      - Makefile
      - .gitlab-ci.yml
      - topic_model/**/*
      - storage/**/*
    refs:
      - master
      - merge_requests
      - tags
      - branches
  script:
    - mc config host add minio ${MINIO_HOST} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY}
    - mc mb minio/testdata
    - MINIO_IP=$(cat /etc/hosts | awk '{if ($2 == "minio") print $1;}')
    - PRED_CID=$(docker run -d -p 5000:5000 --add-host="minio:$MINIO_IP" -e S3ENDPOINTURL=${MINIO_HOST} -e S3OBJECTSTORELOCATION=${TESTBUCKET} -e S3ACCESSKEY=${MINIO_ACCESS_KEY} -e S3SECRETKEY=${MINIO_SECRET_KEY} ${IMAGETAG})
    - sleep 30s
    - echo `docker inspect $PRED_CID` | jq .[0].State
    - OUTPUT=`curl http://docker:5000/predict -d '{"strData":"data=IBM to acquire RedHat. IBM to maintain RedHat strong legacy of opensource innovation. IBM and redhat go in a partnership"}' -H "Content-Type:application/json"`
    - echo $OUTPUT | python -m json.tool
