apiVersion: ailibrary.opendatahub.io/v1alpha1
kind: AILibrary
metadata:
  name: example-ailibrary
spec:
  models:
    - modelname:  anomaly-detection
      enabled: true
      image: quay.io/opendatahub/ai-library-anomaly-detection
      containername: anom-c
      memory: 200Mi
      cpu: 10m
    - modelname:  association-rule-learning
      enabled: false      
      image: quay.io/opendatahub/ai-library-association-rule-learning
      containername: assoc-c
      memory: 200Mi
      cpu: 10m
    - modelname:  correlation-analysis
      enabled: false      
      image: quay.io/opendatahub/ai-library-correlation-analysis
      containername: corr-c
      memory: 200Mi
      cpu: 10m
    - modelname:  duplicate-bug-predict
      enabled: true      
      image: quay.io/opendatahub/ai-library-duplicate-bug-predict
      containername: dupbp-c
      memory: 200Mi
      cpu: 10m
    - modelname:  flakes-predict
      enabled: true      
      image: quay.io/opendatahub/ai-library-flakes-predict
      containername: flakp-c
      memory: 200Mi
      cpu: 10m
    - modelname:  fraud-detection
      enabled: true      
      image: quay.io/opendatahub/ai-library-fraud-detection
      containername: fraud-c
      memory: 200Mi
      cpu: 10m
    - modelname:  matrix-factorization
      enabled: false      
      image: quay.io/opendatahub/ai-library-matrix-factorization
      containername: matrixf-c
      memory: 200Mi
      cpu: 10m
    - modelname:  regression-predict
      enabled: true      
      image: quay.io/opendatahub/ai-library-regression-predict
      containername: regrp-c
      memory: 200Mi
      cpu: 10m
    - modelname: sentiment-analysis
      enabled: true      
      image: quay.io/opendatahub/ai-library-sentiment-analysis
      proxyimage: quay.io/opendatahub/ai-library-sentiment-analysis-proxy
      containername: sent-p      
      memory: 200Mi
      cpu: 10m
      template: sentiment-analysis-deploy.yaml.j2
      model: model-en
    - modelname:  topic-model
      enabled: false      
      image: quay.io/opendatahub/ai-library-topic-model
      containername: anom-c
      memory: 200Mi
      cpu: 10m
  user-interface:
    - enabled: true
      image: quay.io/opendatahub/ai-library-ui:latest
      endpoints:
        regression: http://regression-predict-regression-predict:8000/
        flakes: http://flakes-predict-flakes-predict:8000/
  sample-data:
    enabled: false
    image: quay.io/opendatahub/ai-library-sample-data:latest
    s3_destination_prefix: ""
  s3_endpoint: "http://s3.foo.com:8000"
  s3_access: "YOURS3ACCESSKEYHERE"
  s3_secret: "this1is2just3gibberish"
  s3_bucket: "thisismybucketname"
  s3_region: "myregion"
