---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ai-library-flakes-train
  labels:
    app: ai-library
    component: flakes-train
spec:
  resources:
    limits:
      cpu: 1
      memory: 768Mi
    requests:
      cpu: 1
      memory: 768Mi
  output:
    to:
      kind: ImageStreamTag
      name: "ai-library-flakes-train:latest"
  source:
    type: Git
    git:
      uri: "https://gitlab.com/opendatahub/ai-library.git"
      ref: "master"
    contextDir: "flakes_train"
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-thoth-ubi8-py36:latest
      env:
        - name: ENABLE_PIPENV
          value: '1'
        - name: UPGRADE_PIP_TO_LATEST
          value: ''
        - name: "THOTH_DRY_RUN"
          value: "1"
        - name: "THOTH_ADVISE"
          value: "1"
        - name: "THAMOS_VERBOSE"
          value: "1"
        - name: "THAMOS_DEBUG"
          value: "1"
        - name: "THAMOS_CONFIG_TEMPLATE"
          value: ".thothTemplate.yaml"
        - name: "THAMOS_CONFIG_EXPAND_ENV"
          value: "1"
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
