- name: "Ready to retrieve token from deployed model"
  shell: "curl -XPOST -u {{ key }}:{{ secret }} {{apigateway}}/oauth/token -d grant_type=client_credentials"
  register: result
  
- local_action: copy content={{ result.stdout }} dest="{{ workspace }}/{{model}}.token"
