apiVersion: v1
kind: Template

metadata:
  name: ai-library-ui

parameters:
  - name: APPLICATION_NAME
    value: ai-library-ui
    required: true
  - name: ROUTE_NAME
    value: ui
    required: true
  - name: REPLICAS
    value: "1"
    required: true
  - name: IMAGE_REPOSITORY
    value: quay.io/opendatahub/ai-library-ui:latest
    required: true
  - name: REGRESSOR_URL
    value: http://regrclassifier-m-regrclassifier:8000/
    required: true
  - name: FLAKE_URL
    value: http://predictflakes-m-predictflakes:8000/
    required: true
  - name: KEY
  - name: CERTIFICATE
  - name: CA_CERTIFICATE

objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      replicas: ${{REPLICAS}}
      revisionHistoryLimit: 2
      selector:
        app: ${APPLICATION_NAME}
      strategy:
        rollingParams:
          timeoutSeconds: 3600
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APPLICATION_NAME}
        spec:
          containers:
            - env:
                - name: REGRESSOR_URL
                  value: ${REGRESSOR_URL}
                - name: FLAKE_URL
                  value: ${FLAKE_URL}
              image: ${IMAGE_REPOSITORY}
              imagePullPolicy: Always
              name: ${APPLICATION_NAME}
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
      triggers:
        - type: ConfigChange


  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      ports:
        - name: http
          port: 8080
      selector:
        app: ${APPLICATION_NAME}

  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${ROUTE_NAME}
    spec:
      port:
        targetPort: 8080
      to:
        kind: Service
        name: ${APPLICATION_NAME}
      tls:
        termination: edge
        key: |-
          ${KEY}
        certificate: |-
          ${CERTIFICATE}
        caCertificate: |-
          ${CA_CERTIFICATE}
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None

